### PR TITLE
Register Form PR

### PR DESCRIPTION
**Pull request by Gabkings**
# The Intuit Signup Page

> This is a frontend project with the main aim of learning how to make html5 forms by cloning the Intuit Signup page.
###  Navigation bar

- It has a login button

###  Website Form

- It is displayed.
- It shows the website Logo.
- It shows the signup form Fields
- Terms and Conditions
- Captcha at the bottom

### Website Footer
 - Copy right 
 - Policies Links

### Screenshorts

final
Final2

## Built With

- HTML5,
- CSS3

## Live Demo

[Live Demo Link](https://livedemo.com)

## Getting Started

**This is an example of how you may give instructions on setting up your project locally.**
**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the current project doesn't require testing.**

To get a local copy up and running follow these simple example steps.

### Prerequisites
- HTML5 semantic tags
- CSS3 
- Git Workflow

### Setup
- Clone the repo: ```https://github.com/Gabkings/HTMLFORMS.git ```

### Install
- Open index.htnl with the browser of your choice

## Authors
👤 **Author1**

- Github: [@githubhandle](https://github.com/Gabkings)

- Linkedin: [linkedin](https://www.linkedin.com/in/gabriel-gitonga-b5a611183/)

## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](issues/).

## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Hat tip to anyone who's code was used
- Inspiration
- etc

## 📝 License

This project is [MIT](lic.url) licensed.

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:

### Hey :wave: 

### Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

- [ ]  :one: You need to [Set-up Linter](https://github.com/microverseinc/linters-config/tree/master/css) in order to get this project approved.
  > I can see that you had added a stickler file but your PR is not running through the checks, I recommend you guys to check the [stickler](https://stickler-ci.com/) page to see if you had activated your project in there.
- [ ] :two: The project has to have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

---

#### Page structure

---

##### Sign In Button
- [ ] Adjust color and form to make it look more like original
- [ ] Mising Text
##### Required:
Screenshot from 2020-04-09 20-12-09

##### Yours: 
Screenshot from 2020-04-09 20-12-30

---

##### Intuit products
- [ ] The products row is under the Intuit logo and above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
 > Don't use screen capture

---

### Form

###### Top

- [ ] Fix Aligment, The Learnmore is next to the text above.
- [ ] Fix Text Sizes.

##### Required:
Screenshot from 2020-04-09 20-17-38
##### Yours: 
Screenshot from 2020-04-09 20-17-27

---

###### Bottom
- [ ] It has a disclaimer text that matches the context and style of the original page ([link to page](https://accounts.intuit.com/signup.html))
- [ ] Fix Aligment, The Learnmore is next to the text above.
- [ ] Fix Text Sizes.
##### Required:
Screenshot from 2020-04-09 20-18-40
##### Yours: 
Screenshot from 2020-04-09 20-18-51

---

##### Footer
- [ ] It contains copyright and address information ([link to page](https://accounts.intuit.com/signup.html))


-------------------------------------------

# [OPTIONAL] 

- [ ] Try the use of  the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links
- [ ] Try the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document


-------------------------------------------- 


## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:

### Hey :wave: 

### Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

---

#### Page structure

---

##### Sign In Button

- [ ] Your Login Button and Text is in a fixed position so when I scroll it overlap with the form it should always be on the top right corner 

---

##### Intuit products
- [ ] Make Sure they are properly aligned
- [ ] The products row is under the Intuit logo and above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
 > Don't use screen capture

##### Required:
Screenshot from 2020-04-10 09-07-22
##### Yours: 
Screenshot from 2020-04-10 09-07-10

---

### Form

###### Top

- [ ] Fix Aligment, The Learnmore is next to the text above.
- [ ] Fix Text Sizes.

##### Required:
Screenshot from 2020-04-09 20-17-38
##### Yours: 
Screenshot from 2020-04-09 20-17-27

---


## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by Gabkings** [comment]
Hi, I think you are viewing the wrong link cause am using this link to
clone the project.
Kindly checkit and tell me what am missing there.
https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dhero_sign_up_free_ProspectWeb%26ivid%3D204bd0aa-4352-4f90-9c38-1a2a6a2ef694%26adobe_mc%3DMCORGID%253D969430F0543F253D0A4C98C6%252540AdobeOrg%257CTS%253D1586199621%26ivid%3D204bd0aa-4352-4f90-9c38-1a2a6a2ef694#

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :exploding_head: :checkered_flag:
# Hey  :wave: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:.

### Good Luck in your Next Assignment
### Happy coding:computer: 
#### Daniel Laloush

**Pull request merged**
